# # # # # # # # # # # # # # # #
#   Configuration for Coins   #
# # # # # # # # # # # # # # # #

# What language should the plugin use? And what is your server's currency?
# All available languages can be found in folder 'languages' in the plugin folder.
# Included languages by default: english, dutch, german, spanish, swedish, chinese & hungarian.
language: english
currencySymbol: "$"

# You aren't really going to notice this, but in hoppers you can see its name.
# See a list of all color codes here: http://minecraft.gamepedia.com/Formatting_codes
# 'multiSuffix's parameter will be added behind 'nameOfCoin' in case it's more than one coin.
nameOfCoin: "&6Coin"
multiSuffix: s

# What item will the dropped 'coin' (material) be? Find all materials at:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
coinItem: coin     # coin = sunflower

# This message is sent as action bar, telling the player how much money they have picked up.
# The variable {$} will be replaced by the 'currencySymbol', default: $.
pickupMessage: "&2+ &a{$}%amount%"

# This plugin will drop one coin, being worth what's set at 'moneyAmount'. But here you can
# set that a mob should drop 'moneyAmount's AMOUNT of coins, with each coin being worth $1.
dropEachCoin: false

# The amount of money one coin is worth. Creates a random number between
# 'from' and 'to' which - as money - will be given to the player on pickup.
# However, if 'dropEachCoin' is set to true, killed mobs will drop 'from' to 'to' coins,
# with each coin being worth $1. So by default it will drop 3 to 7 coins when 'dropEachCoin' is true.
moneyAmount:
  from: 3.0
  to: 7.0

# How many decimals should money have? Set to 0 for integers/rounded money (i.e. $3 $6 $8).
# Value 1 (default) means i.e. $2.3 $5.8 $8.0, value of 2 means i.e. $5.23, $3.70, $6.99, etc.
# This setting will be ignored (and set to 0) if 'dropEachCoin' is set to true.
moneyDecimals: 1

# Should coins be stacked? (Or should a coin be one on its own?)
# Stacked coins don't act like one coin. The stack is counted and the worth is multiplied.
# Not stacking coins is just for a cooler effect.
# This setting will be ignored (and set to false) if 'dropEachCoin' is set to true.
stackCoins: false

# Put the amount of coins dropped for a specific mob here, by default: mobs drop one coin.
# ENDER_DRAGON is added by default, meaning that on kill of Ender Dragon, 64 coins drop.
# Set a mob type to 0 (i.e. 'BAT: 0') to disable coins for that specific type.
# You can find mob types via this URL (types that aren't creatures will be ignored):
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
mobMultiplier:
  ENDER_DRAGON: 64
  PLAYER: 3

# When a player gets killed by another player, should (three; setting above) coins drop?
playerDrop: true

# And should coins NOT drop when both players have the same ip address?
# This means that no coin(s) will be dropped if both players are from the same computer.
# This prevents spam killing for unlimited money, unless you use this plugin for a local server.
preventAlts: true

# Should mobs from spawners drop a coin too?
# Mobs from spawners won't drop a coin by default.
# When 'false', mobs can still drop coins when the player (who killed) has permission: 'coins.spawner'.
spawnerDrop: false

# Should passive mobs also drop a coin?
# Passive mobs don't drop a coin by default.
passiveDrop: false

# Play a sound on pickup of a coin.
# This sound is a 1.9+ sound, if you use 1.8, put another sound in there.
# If the sound name remains untouched, and you use 1.8, it will do an 1.8 sound automatically for you.
# Here is a list of 1.9+ sounds: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
pickupSound: true
soundName: "ITEM_ARMOR_EQUIP_GOLD"

# Chance of dropping a coin after a mob has been killed.
# Value from 0.0 to 1.0: 0.0 meaning 0%, 1.0 meaning 100% (so 0.9 meaning 90%).
dropChance: 0.9

# List all worlds you want Coins to be disabled in here.
# Example for disabling two worlds called 'creative' and 'plots':
#    disabledWorlds:
#    - plots
#    - creative
disabledWorlds:

# Lets players use /withdraw <amount> to get a coin "<amount> <coin name>s": for example "53 Coins".
# This allows players to store the coins in chests, but won't be easier to give to others.
# When the coin gets dropped, and picked up after, give the player the amount of money the coin was worth.
enableWithdraw: true
maxWithdrawAmount: 10000.0


#
#   From here kind of doesn't have to do with coins.
#   But it was originally in my Coins package.
#

# Should players lose money on death?
# It shows a title (in the middle of the screen) how much they lost on death.
loseOnDeath: true

# If so, how much will be taken?
moneyTaken:
  from: 10
  to: 30

# The message in the middle of their screen.
deathMessage: "&4- &c{$}%amount%"